function s_function(){
var inbx_val=document.getElementById("txt").value;
var slc_ltr=inbx_val.slice(0,-1);
if(document.getElementById("r_1").checked && document.getElementById("txt").value === 'हाहा'){
document.getElementById("pratipadika").innerHTML='<center><table align=center border=3 bordercolor=lightgreen><tr><th colspan=3 style=background-color:#009999 font-family:Lato,Sans-serif,Sahitya font-size:22px;>आकारान्तशब्दः</th><th style=background-color:red>'+inbx_val+'</th></tr><tr><th style=background-color:#9fdf9f>विभक्तिः</th><th style=background-color:pink>एकवचनम्&nbsp;</th><th style=background-color:pink>द्विवचनम्&nbsp;</th><th style=background-color:pink>बहुवचनम्&nbsp;</th></tr><tr><th style=background-color:#9fdf9f>प्रथमा</th><th>'+inbx_val+'&#x903;&nbsp;'+'</th><th>'+slc_ltr+'&#x94c;&nbsp;'+'</th><th>'+inbx_val+'&#x0903;&nbsp;'+'</th></tr><tr><th style=background-color:#9fdf9f>द्वितीया</th><th>'+inbx_val+'&#x092e;&#x094d;'+'</th><th>'+slc_ltr+'&#x94c;'+'</th><th>'+inbx_val+'&#x0928;&#x094d;'+'</th></tr><tr><th style=background-color:#9fdf9f>तृतीया</th><th>'+inbx_val+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x93e;&#x92e;&#x94d;'+'</th><th>'+inbx_val+'&#x92d;&#x93f;&#x0903;'+'</th></tr><tr><th style=background-color:#9fdf9f>चतुर्थी</th><th>'+slc_ltr+'&#x948;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x93e;&#x92e;&#x94d;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x0903;'+'</th></tr><tr><th style=background-color:#9fdf9f>पञ्चमी</th><th>'+inbx_val+'&#x903;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x93e;&#x92e;&#x94d;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x0903;'+'</th></tr><tr><th style=background-color:#9fdf9f>षष्ठी</th><th>'+inbx_val+'&#x903;'+'</th><th>'+slc_ltr+'&#x94c;&#x903;'+'</th><th>'+inbx_val+'&#x92e;&#x94d;'+'</th></tr><tr><th style=background-color:#9fdf9f>सप्तमी</th><th>'+slc_ltr+'&#x947;'+'</th><th>'+slc_ltr+'&#x94c;&#x903;'+'</th><th>'+inbx_val+'&#x938;&#x941;'+'</th></tr><tr><th style=background-color:#9fdf9f>सम्बोधनम्&nbsp;</th><th>'+inbx_val+'&#x903;'+'</th><th>'+slc_ltr+'&#x094c;'+'</th><th>'+inbx_val+'&#x0903;'+'</th></tr></table></center>';
}
else if(document.getElementById("r_1").checked){
document.getElementById("pratipadika").innerHTML='<center><table align=center border=3 bordercolor=lightgreen><tr><th colspan=3 style=background-color:#009999 font-family:Lato,Sans-serif,Sahitya font-size:22px;>आकारान्तशब्दः</th><th style=background-color:red>'+inbx_val+'</th></tr><tr><th style=background-color:#9fdf9f>विभक्तिः</th><th style=background-color:pink>एकवचनम्&nbsp;</th><th style=background-color:pink>द्विवचनम्&nbsp;</th><th style=background-color:pink>बहुवचनम्&nbsp;</th></tr><tr><th style=background-color:#9fdf9f>प्रथमा</th><th>'+inbx_val+'&#x903;&nbsp;'+'</th><th>'+slc_ltr+'&#x94c;&nbsp;'+'</th><th>'+inbx_val+'&#x0903;&nbsp;'+'</th></tr><tr><th style=background-color:#9fdf9f>द्वितीया</th><th>'+inbx_val+'&#x092e;&#x094d;'+'</th><th>'+slc_ltr+'&#x94c;'+'</th><th>'+slc_ltr+'&#x0903;'+'</th></tr><tr><th style=background-color:#9fdf9f>तृतीया</th><th>'+inbx_val+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x93e;&#x92e;&#x94d;'+'</th><th>'+inbx_val+'&#x92d;&#x93f;&#x0903;'+'</th></tr><tr><th style=background-color:#9fdf9f>चतुर्थी</th><th>'+slc_ltr+'&#x947;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x93e;&#x92e;&#x94d;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x0903;'+'</th></tr><tr><th style=background-color:#9fdf9f>पञ्चमी</th><th>'+slc_ltr+'&#x903;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x93e;&#x92e;&#x94d;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x0903;'+'</th></tr><tr><th style=background-color:#9fdf9f>षष्ठी</th><th>'+slc_ltr+'&#x903;'+'</th><th>'+slc_ltr+'&#x94b;&#x903;'+'</th><th>'+inbx_val+'&#x92f;&#x93e;&#x92e;&#x94d;'+'</th></tr><tr><th style=background-color:#9fdf9f>सप्तमी</th><th>'+slc_ltr+'&#x93f;'+'</th><th>'+slc_ltr+'&#x94b;&#x903;'+'</th><th>'+inbx_val+'&#x938;&#x941;'+'</th></tr><tr><th style=background-color:#9fdf9f>सम्बोधनम्&nbsp;</th><th>'+inbx_val+'&#x903;'+'</th><th>'+slc_ltr+'&#x094c;'+'</th><th>'+inbx_val+'&#x0903;'+'</th></tr></table></center>';
}
else if(document.getElementById("r_2").checked){
document.getElementById("pratipadika").innerHTML='<center><table align=center border=3 bordercolor=lightgreen><tr><th colspan=3 style=background-color:#009999 font-family:Lato,Sans-serif,Sahitya font-size:22px;>आकारान्तशब्दः</th><th style=background-color:red>'+inbx_val+'</th></tr><tr><th style=background-color:#9fdf9f>विभक्तिः</th><th style=background-color:pink>एकवचनम्&nbsp;</th><th style=background-color:pink>द्विवचनम्&nbsp;</th><th style=background-color:pink>बहुवचनम्&nbsp;</th></tr><tr><th style=background-color:#9fdf9f>प्रथमा</th><th>'+inbx_val+'&nbsp;'+'</th><th>'+slc_ltr+'&#x947;&nbsp;'+'</th><th>'+inbx_val+'&#x903;&nbsp;'+'</th></tr><tr><th style=background-color:#9fdf9f>द्वितीया</th><th>'+inbx_val+'&#x092e;&#x094d;'+'</th><th>'+slc_ltr+'&#x947;'+'</th><th>'+inbx_val+'&#x903;'+'</th></tr><tr><th style=background-color:#9fdf9f>तृतीया</th><th>'+slc_ltr+'&#x92f;&#x93e;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x93e;&#x92e;&#x94d;'+'</th><th>'+inbx_val+'&#x92d;&#x93f;&#x0903;'+'</th></tr><tr><th style=background-color:#9fdf9f>चतुर्थी</th><th>'+inbx_val+'&#x92f;&#X948;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x93e;&#x92e;&#x94d;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x0903;'+'</th></tr><tr><th style=background-color:#9fdf9f>पञ्चमी</th><th>'+inbx_val+'&#x92f;&#x93e;&#x903;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x93e;&#x92e;&#x94d;'+'</th><th>'+inbx_val+'&#x92d;&#x94d;&#x92f;&#x0903;'+'</th></tr><tr><th style=background-color:#9fdf9f>षष्ठी</th><th>'+inbx_val+'&#x92f;&#x93e;&#x903;'+'</th><th>'+slc_ltr+'&#x92f;&#x94b;&#x903;'+'</th><th>'+inbx_val+'&#x928;&#x93e;&#x92e;&#x94d;'+'</th></tr><tr><th style=background-color:#9fdf9f>सप्तमी</th><th>'+inbx_val+'&#x92f;&#x93e;&#x92e;&#x94d;'+'</th><th>'+slc_ltr+'&#x92f;&#x94b;&#x903;'+'</th><th>'+inbx_val+'&#x938;&#x941;'+'</th></tr><tr><th style=background-color:#9fdf9f>सम्बोधनम्&nbsp;</th><th>'+slc_ltr+'&#x947;'+'</th><th>'+slc_ltr+'&#x947;'+'</th><th>'+inbx_val+'</th></tr></table></center>';
}
else{
document.getElementById("pratipadika").innerHTML='<center style=color:#ffffff><p style=background-color:#009999  font-family:Lato,Sans-serif,Sahitya font-size:22px;>कृपया कञ्चिदेकं विकल्पं रेडियोगण्डं  चिनोतु ।</center></p>';
}
};
